### ISSUE TITLE
nvidia-container-runtime segfault

### ISSUE THREAD

**Issue by xhejtman** [NVIDIA/libnvidia-container#228]
Hello,

I am getting randomly:
```
[4746547.221468] nvidia-containe[2847336]: segfault at 7f6ee8000020 ip 00007f6f24ca1cf2 sp 00007f6ef7ffed60 error 6 in libc.so.6[7f6f24c28000+195000] likely on CPU 127 (core 31, socket 1)
```

is is not related to a particular pod, I think this is result of some monitoring action (liveness/readiness probes). It is hard to debug as there is no core dump file.

Version is 1.14.3.

**Comment by elezar** [comment]
@xhejtman could you describe your environment?

Is this happening sporadically, or can it be reproduced?

**Comment by xhejtman** [comment]
Sporadically, but quite often. It may happen, that two probes run in parallel and sometimes it segfaults.

It is kubernetes 1.26.9 using RKE2. Gpu operator 23.6.1, but I tried today nvidia toolkit from the latest gpu-operator. 

I can test or provide logs if needed.

**Comment by jokester** [comment]
I experienced a similar error today.

In my case it happens every time I start a GPU-using ollama container. Besides the error in dmesg, the container freeze a long time in `created` state, and eventually fails to start.

My dmesg:

```
[  657.997665] nvidia-containe[17585]: segfault at 0 ip 00007cac59ab4398 sp 00007ffe56b394b0 error 4 in libnvidia-container.so.1.17.7[a398,7cac59aae000+15000] likely on CPU 9 (core 1, socket 0)
[  657.997677] Code: 00 8b 00 89 85 38 fe ff ff f6 c4 80 0f 85 d8 01 00 00 48 8d 85 50 fe ff ff 48 89 85 18 fe ff ff 48 8b 85 18 fe ff ff 4c 8b 00 <41> 80 38 40 0f 84 ea 01 00 00 ba f6 01 00 00 bf 49 00 00 00 48 8b
```

My packages (all from Archlinux official package repo):

```
Name            : linux
Version         : 6.14.6.arch1-1   -- last upgraded 11 days ago

Name            : nvidia-container-toolkit
Version         : 1.17.7-1         -- suspicious: upgraded yesterday from 1.17.6-1

Name            : docker
Version         : 1:28.1.1-1       -- last upgraded 1 month ago

Name            : libnvidia-container
Version         : 1.17.7-1         -- suspicious: upgraded yesterday from 1.17.6-1
```

The container, taken from `docker-compose config` output:

```yml

services:
  ollama:
    container_name: ollama:0.7.0    -- https://hub.docker.com/layers/ollama/ollama/0.7.0/images/sha256-f8da1dda0daef13c49859cbc722e4ba7d7a3d2a0174e7064f6d3a99d93653e1e
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: 1
    image: ollama/ollama:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 11434
        published: "11434"
        protocol: tcp
    restart: unless-stopped
    tty: true
```
