### ISSUE TITLE
BLITTING vs. FLIPPING in containers (lxd and docker)

### ISSUE THREAD

**Issue by mismacku** [NVIDIA/libnvidia-container#61]
Hello. Thanks for reading and thanks for all of the nvidia container work!  
  
I've had trouble over the last few years trying to get GLX apps to perform well in lxd and docker containers. It seems in containers, the driver insists on BLITTING vs. FLIPPING as opposed to running on the host where it always indicates **FLIP**. I posted a few issues over in the lxd world and Stephane recommended I post here.  In short, regardless of the GLX app I run in lxc and docker, I cannot get the driver to FLIP. Any ideas or additional information I can provide?  

https://github.com/lxc/lxd/issues/5988  
https://github.com/lxc/lxd/issues/3826  
  
**Version info:**  
- Distribution: Ubuntu
- Distribution version: 16.04.6
- Nvidia P5000 and K5000
- Nvidia driver: 418.67
- cuda version: 10.1
- kernel: 4.15.0-15
```
apt-cache policy libnvidia-container-tools
libnvidia-container-tools:
  Installed: 1.0.2-1

apt-cache policy libnvidia-container1
libnvidia-container1:
  Installed: 1.0.2-1

apt-cache policy nvidia-docker2
nvidia-docker2:
  Installed: 2.0.3+docker18.09.7-3
```
# Steps to reproduce
**lxc**
1. using nvidia-settings under OpenGL Settings, tick Enable Graphics API Visual Indicator
1. Use the lxc profile below
1. start an Ubuntu 18.04 container
1. apt install glmark2
1. run glmark (glmark2 --fullscreen)
1. notice the visual indicator shows BLIT - VSYNC OFF  

**docker**
`nvidia-docker run -it --privileged --rm --env='DISPLAY=:0' --volume='/tmp/.X11-unix:/tmp/.X11-unix' glxgears glxgears -fullscreen`  

Note: the VI shows BLIT regardless of the GLX app I'm running (glxgears, glmark2, in-house GLX apps)  

**lxc profile**
```
config:
  environment.DISPLAY: :0
  nvidia.driver.capabilities: compute, display, graphics, utility, video
  nvidia.runtime: "true"
description: Default LXD profile
devices:
  X0:
    path: /tmp/.X11-unix/X0
    source: /tmp/.X11-unix/X0
    type: disk
  Xauthority:
    path: /root/.Xauthority
    source: /home/oblong/.Xauthority
    type: disk
  eth0:
    name: eth0
    nictype: macvlan
    parent: enp0s25
    type: nic
  gpu:
    type: gpu
  root:
    path: /
    pool: default
    type: disk
name: default
```
